version: '3.7'
 
services:
    nginx:
        container_name: nginx
        build: ./custom-url-shortner/nginx
        ports:
            - '80:80'
        restart: always
    
    application_server:
        container_name: shortner 
        depends_on: 
            - nginx
        build: ./custom-url-shortner/application_server
        ports:
          - '3000:3000'
        restart: always

    mongo:
        image: mongo
        container_name: database
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: root
        restart: always
    
    redis:
        build: ./custom-url-shortner/redis
        container_name: redisCache
        restart: always
        