version: '3.7'
 
services:
    nginx:
        container_name: nginx
        build: ./nginx
        ports:
            - '80:80'
        restart: always
    
    application_server:
        container_name: shortner 
        depends_on: 
            - nginx
        build: ./application_server
        ports:
          - '3000:3000'
        restart: always
    
    web_server:
        container_name: web_server
        build: ./web_server
        ports:
          - '5000:5000'
        restart: always
